name: branch
on:
  push:
    branches-ignore:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pg_exec_array_params_test
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      matrix:
        ruby: [ '2.7' ]
        pg: [ '>= 1' ]
    name: Ruby ${{ matrix.ruby }}, pg ${{ matrix.pg }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ matrix.ruby }}-${{ matrix.pg }}-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-${{ matrix.ruby }}-${{ matrix.pg }}
      - name: Test
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pg_exec_array_params_test
          PG: ${{ matrix.pg }}
          PG_GEM_VERSION: ${{ matrix.pg }}
          CI: true
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3 --without benchmark
          bundle exec rake ci
